import { Seat, Session, WorkItem, Artifact, Handoff, CanonicalEvent, InboxItem } from './types';

// Legacy standalone mock exports kept aligned with the current 2026-04-28 coordination narrative.

export const mockSeats: Seat[] = [
  { id: 'seat-1', name: 'lyra', role: 'ProductOwner', status: 'Active', created_at: '2026-04-20T10:00:00+08:00' },
  { 
    id: 'seat-2', 
    name: 'nimbus', 
    role: 'Architect', 
    status: 'Active', 
    created_at: '2026-04-20T10:00:00+08:00',
    capabilities: ['架构对齐 (Architecture Alignment)', '工程设计', '差异分析'],
    accepted_input_types: ['PRD v0.5', '交互规格书', '验收标准'],
    output_types: ['架构设计文档', 'ADR (决策记录)', '构建清单'],
    input_budget: 500000,
    output_budget: 200000,
    constraints: ['必须使用文件优先的证据链', '严禁在未授权情况下进行重构'],
    attached_skills: ['基线巩固 (Baseline Consolidation)', '跨席位依赖拆解'],
  },
  { id: 'seat-3', name: 'mira', role: 'Designer', status: 'Paused', created_at: '2026-04-20T10:00:00+08:00' },
  { id: 'seat-4', name: 'flux', role: 'Verifier', status: 'Active', created_at: '2026-04-20T10:00:00+08:00' },
  { id: 'seat-5', name: 'aegis', role: { Custom: '阶段闸门复核' }, status: 'Paused', created_at: '2026-04-24T09:00:00+08:00' },
];

export const mockSessions: Session[] = [
  {
    id: 'ses-401',
    seat_id: 'seat-1',
    runtime: 'Codex',
    workspace_path: '~/Documents/GitHub/seatloom',
    branch: 'coord/lyra-drive',
    status: 'Running',
    pid: 58421,
    created_at: '2026-04-28T09:10:00+08:00',
  },
  {
    id: 'ses-402',
    seat_id: 'seat-3',
    runtime: 'GeminiCli',
    workspace_path: '~/Documents/GitHub/seatloom/ui',
    branch: 'design/v5.2',
    status: 'Interrupted',
    created_at: '2026-04-28T11:15:00+08:00',
    ended_at: '2026-04-28T14:05:00+08:00',
  },
  {
    id: 'ses-403',
    seat_id: 'seat-4',
    runtime: { Custom: 'OpenCode-DSV4Pro' },
    workspace_path: '~/Documents/GitHub/seatloom',
    branch: 'repair/sg-01-ui',
    status: 'Running',
    pid: 60218,
    created_at: '2026-04-28T15:40:00+08:00',
  },
  {
    id: 'ses-406',
    seat_id: 'seat-1',
    runtime: 'Codex',
    workspace_path: '~/Documents/GitHub/seatloom/ui',
    branch: 'demo/zh-density-pass',
    status: 'Running',
    pid: 61345,
    created_at: '2026-04-28T20:12:00+08:00',
  },
  {
    id: 'ses-407',
    seat_id: 'seat-2',
    runtime: 'ClaudeCode',
    workspace_path: '~/Documents/GitHub/seatloom',
    branch: 'arch/v0.5-sync',
    status: 'InputRequired',
    created_at: '2026-04-28T21:15:00+08:00',
    prompt_state: {
      classification: 'deterministic',
      policy: 'needs_approval',
      preview: '检测到 docs/architecture-design.md 中存在未提交的更改。\n是否要在继续之前暂存这些更改？\n1. 是，全部暂存\n2. 否，跳过暂存\n3. 中止',
      expected_next: '正在生成用于 v0.5 对齐的更新版 ADR...',
      step_count: 12,
      token_budget: 15000,
    }
  },
  {
    id: 'ses-408',
    seat_id: 'seat-1',
    runtime: 'Codex',
    workspace_path: '~/Documents/GitHub/seatloom',
    branch: 'main',
    status: 'Running',
    created_at: '2026-04-28T22:05:00+08:00',
    continuity_pack: {
      tier_0_identity: {
        seat_id: 'seat-1',
        runtime: 'Codex',
        workItem_id: 'wi-410',
        branch: 'main'
      },
      tier_1_state: {
        ac_progress: ['AC-01 通过', 'AC-02 通过', 'AC-03 通过'],
        latest_commit: '7a2b9d1',
        current_blocker: '无'
      },
      tier_2_decisions: {
        summary: '统一使用 template+subtype 双键作为所有协调产物的真值索引，禁止路径裸传。',
        evidence_refs: ['docs/coordination/DOCUMENT_TEMPLATES.md']
      },
      seat_skills: ['产品完整性控制', '评审环路管理'],
      playbook_matches: ['冷启动 R0 序列'],
      budget_estimate: 250000,
      fallback_path: 'docs/PRODUCT_TRUTH.md'
    }
  }
];

export const mockWorkItems: WorkItem[] = [
  {
    id: 'wi-401',
    title: 'SG-01 界面合同修复（代 Mira 执行）',
    goal: '在不改动侧栏/主区信息架构的前提下，修复终端面板、收件箱跳转、活动时间线筛选与交互真值问题。',
    acceptance_criteria: [
      '终端面板必须作为底部可折叠面板存在。',
      '收件箱任意条目都能跳转到真实详情对象。',
      '修复说明必须写回 `docs/coordination/`。',
    ],
    owner_seat_id: 'seat-4',
    status: 'InReview',
    priority: 'Critical',
    depends_on: [],
    created_at: '2026-04-28T10:10:00+08:00',
    updated_at: '2026-04-28T17:46:00+08:00',
  },
  {
    id: 'wi-402',
    title: 'Flux 交付验收复核与 Nimbus 放行判定',
    goal: '对照 PRD v0.4、交互规格与验收规格给出清晰的通过 / 保持阻塞结论。',
    acceptance_criteria: [
      '必须输出关键流程覆盖矩阵。',
      '阻塞项必须带文件定位。',
      '明确 Nimbus 是否可以进入工程接力。',
    ],
    owner_seat_id: 'seat-1',
    status: 'Active',
    priority: 'Critical',
    depends_on: ['wi-401'],
    created_at: '2026-04-28T15:55:00+08:00',
    updated_at: '2026-04-28T20:18:00+08:00',
  },
  {
    id: 'wi-406',
    title: '中文演示数据与真实量级刷新',
    goal: '把主视图从英文轻量样例切换成与 2026-04-28 协调日志一致的中文高密度叙事。',
    acceptance_criteria: [
      '主视图默认中文，不再出现明显中英混杂。',
      '收件箱、工作项、活动时间线和详情面板具备接近真实工作的信息量。',
      '文案和数量与今日协调日志保持一致。',
    ],
    owner_seat_id: 'seat-1',
    status: 'Active',
    priority: 'High',
    depends_on: ['wi-405'],
    created_at: '2026-04-28T18:42:00+08:00',
    updated_at: '2026-04-28T20:36:00+08:00',
  },
  {
    id: 'wi-407',
    title: '字体、字号与信息密度统一校正',
    goal: '解决中英字重不协调、标签过小、正文难读的问题，让真实信息量增加后仍然易读。',
    acceptance_criteria: [
      '标题、正文、标签形成明确层级。',
      '中文界面在桌面与移动端均保持可读。',
      '回传前后差异说明供 Lyra 验收。',
    ],
    owner_seat_id: 'seat-4',
    status: 'Ready',
    priority: 'High',
    depends_on: ['wi-406'],
    created_at: '2026-04-28T18:34:00+08:00',
    updated_at: '2026-04-28T18:34:00+08:00',
  },
  {
    id: 'wi-411',
    title: 'v0.5 UI 核心表面对齐校验',
    goal: '根据 S5A-S5E 的实现反馈，对已修复的表面进行最终语义对齐校验。',
    acceptance_criteria: [
      'Handoff 状态条显示准确',
      'WorkItem 评审阶层记录可见',
      'Session 提示阻塞与启动包预览正常'
    ],
    owner_seat_id: 'seat-1',
    status: 'Active',
    priority: 'High',
    depends_on: ['wi-410'],
    created_at: '2026-04-28T22:15:00+08:00',
    updated_at: '2026-04-28T22:20:00+08:00',
    change_tier_record: {
      tier: 'L2',
      reason: '根据 S5A-S5E 实现反馈，需要对部分交互细节做二次语义对齐。',
      changed_clauses: ['UX-06', 'UX-12', 'INT-16'],
      impact_level: 'Medium',
      executor: { Seat: 'seat-3' },
      reviewer: { Seat: 'seat-1' },
      ack_mode: 'CompactAck',
      evidence_refs: ['docs/coordination/tasks/mira/MIRA-2026-04-28-serial-restart-s5-queue-control-v1.md']
    }
  }
];

export const mockArtifacts: Artifact[] = [
  {
    id: 'ar-401',
    title: 'SG-01 代 Mira 修补交付说明',
    template: 'T3',
    subtype: 'verification',
    status: 'delivered',
    author: 'flux',
    date: '2026-04-28',
    version: 'v1',
    tags: ['sg-01', 'repair', 'delivery'],
    summary: '说明代 Mira 修补包的交付范围、变更文件和构建验证结论。',
    storage_path: 'docs/coordination/tasks/flux/FLUX-2026-04-28-acting-mira-contract-repair-delivery-v1.md',
    created_at: '2026-04-28T17:38:00+08:00',
  },
  {
    id: 'ar-402',
    title: 'Flux 反馈恢复记录',
    template: 'T4',
    subtype: 'gap_review',
    status: 'recovered',
    author: 'lyra',
    date: '2026-04-28',
    version: 'v1',
    tags: ['feedback', 'recovery', 'review'],
    summary: '把 Flux 的即时反馈恢复为可追溯评审文件，供后续验收与追责使用。',
    storage_path: 'docs/coordination/reviews/2026-04-28-flux-feedback-recovery.md',
    created_at: '2026-04-28T18:02:00+08:00',
  },
  {
    id: 'ar-403',
    title: '前端中文高密度数据刷新方案',
    template: 'T3',
    subtype: 'integration',
    status: 'in_progress',
    author: 'lyra',
    date: '2026-04-28',
    version: 'v2',
    tags: ['frontend', 'demo-data', 'zh'],
    summary: '定义前端中文高密度数据与真实量级刷新方案，作为当前演示叙事的内容基线。',
    storage_path: 'docs/coordination/tasks/lyra/LYRA-2026-04-28-frontend-demo-data-v2.md',
    created_at: '2026-04-28T20:28:00+08:00',
  },
];

export const mockHandoffs: Handoff[] = [
  {
    id: 'ho-401',
    from_ref: { Seat: 'seat-1' },
    to_ref: { Seat: 'seat-4' },
    workitem_id: 'wi-401',
    purpose: '按 Lyra 审批过的修补清单执行代 Mira 合同修复，严格保持信息架构不变。',
    expected_outcome: '交付通过构建验证的 P0 / P1 修补结果，并附带可追溯交付说明。',
    artifact_ids: ['ar-401'],
    required_receipt: true,
    status: 'Completed',
    created_at: '2026-04-28T10:25:00+08:00',
    sent_at: '2026-04-28T10:30:00+08:00',
  },
  {
    id: 'ho-402',
    from_ref: { Seat: 'seat-4' },
    to_ref: { Seat: 'seat-1' },
    workitem_id: 'wi-402',
    purpose: 'Flux 已完成代 Mira 修复交付，请 Lyra 执行正式验收复核。',
    expected_outcome: '给出明确的通过 / 保持阻塞结论，并决定 Nimbus 是否可以接手。',
    artifact_ids: ['ar-402'],
    required_receipt: true,
    status: 'Received',
    created_at: '2026-04-28T17:35:00+08:00',
    sent_at: '2026-04-28T17:40:00+08:00',
  },
  {
    id: 'ho-404',
    from_ref: { Seat: 'seat-1' },
    to_ref: { Seat: 'seat-4' },
    workitem_id: 'wi-407',
    purpose: '统一原型中的中文字体、字号和信息密度，消除阅读疲劳。',
    expected_outcome: '回传一轮带前后差异说明的视觉微调结果。',
    artifact_ids: ['ar-403'],
    required_receipt: true,
    status: 'Sent',
    created_at: '2026-04-28T18:34:00+08:00',
    sent_at: '2026-04-28T18:36:00+08:00',
  },
];

export const mockEvents: CanonicalEvent[] = [
  {
    event_id: 'ev-401',
    event_type: 'WorkItemCreated',
    occurred_at: '2026-04-28T10:10:00+08:00',
    actor_ref: { Seat: 'seat-1' },
    object_refs: [{ WorkItem: 'wi-401' }],
    evidence_refs: ['docs/coordination/tasks/flux/FLUX-2026-04-28-acting-mira-contract-repair-v1.md'],
    payload: { title: 'Lyra 建立代 Mira 合同修复工作项，并冻结信息架构边界。' },
  },
  {
    event_id: 'ev-402',
    event_type: 'SessionInterrupted',
    occurred_at: '2026-04-28T14:05:00+08:00',
    actor_ref: { Seat: 'seat-3' },
    object_refs: [{ Session: 'ses-402' }],
    evidence_refs: [],
    payload: { title: 'Mira 原会话达到限制后中断，等待临时替补席位接手。' },
  },
  {
    event_id: 'ev-403',
    event_type: 'HandoffSent',
    occurred_at: '2026-04-28T17:40:00+08:00',
    actor_ref: { Seat: 'seat-4' },
    object_refs: [{ Handoff: 'ho-402' }, { WorkItem: 'wi-402' }],
    evidence_refs: ['docs/coordination/tasks/flux/FLUX-2026-04-28-acting-mira-contract-repair-delivery-v1.md'],
    payload: { title: 'Flux 向 Lyra 发送代 Mira 修复交付，等待正式验收。' },
  },
  {
    event_id: 'ev-404',
    event_type: 'ReconcileCompleted',
    occurred_at: '2026-04-28T20:28:00+08:00',
    actor_ref: { Seat: 'seat-1' },
    object_refs: [{ WorkItem: 'wi-406' }, { Session: 'ses-406' }],
    evidence_refs: ['docs/coordination/tasks/lyra/LYRA-2026-04-28-frontend-demo-data-v2.md'],
    payload: { title: 'Lyra 完成前端中文高密度数据对账，准备继续做文件写回。' },
  },
];

export const mockInboxItems: InboxItem[] = [
  {
    id: 'inbox-1',
    priority: 'Critical',
    type: '交接待回执',
    actor: 'flux -> lyra',
    object_ref: 'HO-402',
    summary: '代 Mira 修复交付已送达，等待正式验收结论。',
    timestamp: '17:40',
  },
  {
    id: 'inbox-2',
    priority: 'Critical',
    type: '验收待决策',
    actor: 'lyra',
    object_ref: 'WI-402',
    summary: '需要明确给出通过 / 保持阻塞结论，并决定 Nimbus 是否放行。',
    timestamp: '20:18',
  },
  {
    id: 'inbox-3',
    priority: 'Normal',
    type: '输入请求',
    actor: 'flux',
    object_ref: 'HO-404',
    summary: '请确认字体、字号与信息密度统一的目标口径。',
    timestamp: '18:36',
  },
  {
    id: 'inbox-4',
    priority: 'Low',
    type: '状态同步',
    actor: 'seatloom',
    object_ref: 'WI-406',
    summary: '中文演示数据刷新已进入写回阶段，待补充记忆日志与产物记录。',
    timestamp: '20:28',
  },
];
